# Generated by Django 3.0.4 on 2020-03-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('year', models.IntegerField()),
                ('category', models.CharField(choices=[('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Trucks', 'Trucks')], max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('price', models.IntegerField()),
                ('horsepower', models.IntegerField()),
                ('mpg', models.IntegerField(help_text='Combined Fuel Economy')),
                ('des', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=32)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
