# Generated by Django 3.0.4 on 2020-03-20 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_auto_20200320_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
    ]
