# Generated by Django 3.0.4 on 2020-03-20 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_remove_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
