# Generated by Django 3.0.5 on 2020-04-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_auto_20200408_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='detailImgs',
        ),
        migrations.AlterField(
            model_name='carimage',
            name='img',
            field=models.ImageField(default='cars/1.png', upload_to='cars/'),
        ),
    ]
