# Generated by Django 3.0.5 on 2020-04-10 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_auto_20200409_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('pickedUp', models.BooleanField(default=False)),
                ('createTime', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createTime'],
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Order_Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('total', models.IntegerField()),
                ('commented', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Car')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='Backend.Order')),
            ],
        ),
    ]
