# Generated by Django 3.0.5 on 2020-04-10 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_auto_20200410_0353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='createTime',
        ),
    ]
