# Generated by Django 3.0.5 on 2020-04-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_auto_20200411_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_car',
            name='commented',
        ),
    ]
