# Generated by Django 3.0.5 on 2020-04-17 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0019_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Backend.Cart'),
        ),
    ]
