# Generated by Django 3.0.5 on 2020-04-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20200326_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(default='cars/1.png', upload_to='cars/'),
        ),
    ]
