# Generated by Django 3.0.5 on 2020-04-07 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20200406_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='exteriorColor',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='car',
            name='interiorColor',
        ),
    ]
