# Generated by Django 3.0.5 on 2020-04-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_auto_20200410_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
