# Generated by Django 3.0.5 on 2020-04-11 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_auto_20200410_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='firstName',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='lastName',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='des',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
