# Generated by Django 3.0.5 on 2020-04-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_remove_order_car_commented'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='Backend.Order'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Order_Car',
        ),
    ]
