INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (1, 'RAV4', 2020, 'Toyota', 'SUV', '2.5L 4-Cyl', 27025, 203, 28, 'Gasoline', 'Second Row Seating', 'FWD', 'Super White', '2.5L I4 16V PDI DOHC', '8-Speed Automatic', 'LD049853', 'JTMC1RFV1LD049853', 0, 3, 'cars/1.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (2, 'CR-V', 2020, 'Honda', 'SUV', 'EX 4-Cyl, Turbo, 1.5 Liter', 26985, 190, 30, 'Gasoline', 'Second Row Seating', 'FWD', 'Modern Steel', '1.5L I4 16V GDI DOHC Turbo', 'Automatic CVT', '200560', '5J6RW1H50LA006448', 4, 3, 'cars/2.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (3, 'Forester', 2020, 'Subaru', 'SUV', 'Base Style
4-Cyl, 2.5 Liter', 24500, 182, 29, 'Gasoline', 'Second Row Seating', 'FWD', 'Jasper Green Metallic', '2.5L H4 16V GDI DOHC', 'Automatic CVT', 'S35828', 'JF2SKAGC4LH503949', 0, 3, 'cars/3.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (4, 'Corolla', 2020, 'Toyota', 'Sedan', 'LE
4-Cyl, 1.8 Liter', 19000, 169, 32, 'Gasoline', 'Second Row Seating', 'FWD', 'Blizzard Pearl', '1.8L I4 16V MPFI DOHC', 'Automatic CVT', 'T5467', '5YFEPRAE2LP062784', 0, 3, 'cars/4.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (5, 'Accord', 2020, 'Honda', 'Sedan', 'LX
4-Cyl, i-VTEC, Turbo, 1.5 Liter', 23000, 192, 33, 'Gasoline', 'Second Row Seating', 'FWD', 'Platinum White Pearl', '1.5L I4 16V GDI DOHC Turbo', '6-Speed Manual', 'LA012282', '1HGCV1E37LA012282', 28, 3, 'cars/5.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (6, 'Maxima', 2020, 'Nissan', 'Sedan', 'SV
V6, 3.5 Liter', 35000, 300, 24, 'Gasoline', 'Second Row Seating', 'FWD', 'Gun Metallic', '3.5L V6 24V GDI DOHC', 'Automatic CVT', '85331', '1N4AA6AVXKC379823', 199, 3, 'cars/6.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (7, 'Rio', 2020, 'Kia', 'Hatchback', 'S
4-Cyl, 1.6 Liter ', 16700, 120, 36, 'Gasoline', 'Second Row Seating', 'FWD', 'Deep Sea Blue', '1.6L I4 16V MPFI DOHC', 'Automatic CVT', '7558', '3KPA25AD1LE272940', 5, 3, 'cars/7.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (8, 'Yaris', 2020, 'Toyota', 'Hatchback', 'LE
4-Cyl,MultiAir, Turbo, 1.4 Liter', 15700, 135, 32, 'Gasoline', 'Second Row Seating', 'FWD', 'Frost', 'Regular Unleaded I-4 1.5 L/91', 'Automatic', '20210', '3MYDLBJV6LY702091', 0, 3, 'cars/8.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (9, 'Spark
', 2020, 'Chevrolet', 'Hatchback', 'LS
4-Cyl, ECOTEC, 1.4 Liter ', 13000, 98, 33, 'Gasoline', 'Second Row Seating', 'FWD', 'Raspberry', '1.4L I4 16V MPFI DOHC', 'Automatic CVT', '1-2151', 'KL8CB6SA2LC419365', 0, 3, 'cars/9.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (10, '1500 Crew Cab', 2020, 'Ram', 'Trucks', 'Big Horn
V6, VVT, eTorque, 3.6 Liter', 37500, 260, 17, 'Gasoline', 'Second Row Seating', '4WD', 'Crystal Metallic', '3.6L V8 16V MPFI OHV', '8-Speed Automatic', 'KN846494', '1C6SRFFT5KN846494', 21, 3, 'cars/10.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (11, 'F150 SuperCrew Cab', 2020, 'Ford', 'Trucks', 'XL
V6, EcoBoost, 3.5 Liter', 45000, 250, 18, 'Gasoline', 'Second Row Seating', 'FWD', 'Ruby Red Metallic', '3.5L V6 24V PDI DOHC Twin Turbo', '10-Speed Automatic', 'KKF09277', '1FTEW1E44KKF09277', 17, 3, 'cars/11.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (12, 'Tacoma Access Cab', 2020, 'Toyota', 'Trucks', 'SR
4-Cyl, 2.7 Liter', 28000, 159, 20, 'Gasoline', 'Second Row Seating', '4WD', 'Quicksand', '3.5L V6 24V PDI DOHC', '6-Speed Automatic', 'L413', '5TFSZ5AN0LX224712', 0, 3, 'cars/12.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (13, 'Camry', 2021, 'Toyota', 'Sedan', 'XSE4-Cyl, 2.5 Liter', 32574, 301, 25, 'Gasoline', 'Second Row Seating', 'FWD', 'Midnight Black Metallic', '2.5L I4 16V PDI DOHC', '8-Speed Automatic', 'LU939099', '4T1K61AK7LU939099', 5, 5, 'cars/13.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (14, 'Sequoia', 2020, 'Toyota', 'SUV', 'SR5
V8, 5.7 Liter ', 46871, 381, 15, 'Gasoline', 'Second Row Seating', 'RWD', 'Magnetic Gray Metallic', '5.7L V8 32V MPFI DOHC', '6-Speed Automatic', 'LS074506', '5TDKY5G16LS074506', 10, 3, 'cars/14.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (15, 'Pilot', 2020, 'Honda', 'SUV', 'EX-L
V6, i-VTEC, 3.5 Liter', 35919, 280, 23, 'Gasoline', 'Second Row Seating', 'FWD', 'Platinum White Pearl', '3.5L V6 24V GDI SOHC', '6-Speed Automatic', '200580', '5FNYF5H54LB020479', 0, 3, 'cars/15.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (16, 'Land Cruiser', 2020, 'Toyota ', 'SUV', 'Heritage Edition
V8, 5.7 Liter', 91508, 380, 14, 'Gasoline', 'Second Row Seating', 'FWD', 'Black', '5.7L V8 32V MPFI DOHC', '8-Speed Automatic', '32014', 'JTMCY7AJ2L4090304', 0, 3, 'cars/16.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (17, 'Flex', 2019, 'Ford', 'SUV', 'Limited
V6, 3.5 Liter', 34995, 287, 19, 'Gasoline', 'Third Row Seating', 'FWD', 'Blue Metallic', '3.5L V6 Cylinder Engine', 'Automatic', 'KBA37321', '2FMGK5D81KBA37321', 7, 3, 'cars/17.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (18, 'Fusion', 2020, 'Ford', 'Sedan', 'SE
4-Cyl, EcoBoost, Turbo, 1.5 Liter', 20749, 312, 23, 'Gasoline', 'Second Row Seating', 'FWD', 'Black Metallic', '1.5L I4 16V GDI DOHC Turbo', '6-Speed Automatic', 'U327', '3FA6P0HD6LR159807', 3, 3, 'cars/18.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (19, 'Taurus', 2019, 'Ford', 'Sedan', 'SE
V6, 3.5 Liter', 16651, 288, 21, 'Gasoline', 'Second Row Seating', 'FWD', 'Oxford White', '3.5L V6 24V MPFI DOHC', '6-Speed Automatic', '00191593', '1FAHP2D88KG117643', 0, 3, 'cars/19.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (20, 'Explorer', 2020, 'Ford', 'SUV', 'XLT
4-Cyl, EcoBoost, Turbo, 2.3 Liter', 33848, 300, 24, 'Gasoline', 'Second Row Seating', 'RWD', 'Silver Metallic', '2.3L I4 16V GDI DOHC Turbo', '10-Speed Automatic', 'GA52780', '1FMSK7DH9LGA52780', 20, 3, 'cars/20.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (21, 'Focus', 2018, 'Ford', 'Sedan', 'SEL Sedan 4D
4-Cyl, 2.0 Liter', 16254, 160, 28, 'Gasoline', 'Second Row Seating', 'FWD', 'Oxford White', '2.0L I4 16V GDI DOHC', '6-Speed PowerShift Automatic', '10930', '1FADP3F2XJL257289', 22, 3, 'cars/21.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (22, 'Insight', 2020, 'Honda', 'Sedan', 'Touring
4-Cyl, Hybrid, 1.5 Liter', 29295, 107, 52, 'Gasoline', 'Second Row Seating', 'FWD', 'Crimson Pearl', 'Gas/Electric I-4 1.5 L/91', 'Variable', 'LE011530', '19XZE4F93LE011530', 1, 3, 'cars/22.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (23, 'Passport', 2020, 'Honda', 'SUV', 'EX-L
V6, i-VTEC, 3.5 Liter', 36229, 280, 22, 'Gasoline', 'Second Row Seating', 'FWD', 'Deep Scarlet Pearl', 'Regular Unleaded V-6 3.5 L/212', 'Automatic', '409687', '5FNYF8H59LB009687', 10, 3, 'cars/23.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (24, 'Ridgeline', 2020, 'Honda', 'Trucks', 'RTL-E
V6, i-VTEC, 3.5 Liter', 38021, 280, 22, 'Gasoline', 'Second Row Seating', 'AWD', 'Modern Steel', '3.5L V6 24V GDI SOHC', '9-Speed Automatic', 'H20306', '5FPYK3F79LB004077', 7, 3, 'cars/24.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (25, 'Fit', 2020, 'Honda', 'Hatchback', 'LX
4-Cyl, i-VTEC, 1.5 Liter', 17595, 170, 36, 'Gasoline', 'Second Row Seating', 'FWD', 'Aegean Blue Metallic', '1.5L I4 16V GDI DOHC Turbo', 'Automatic CVT', '200532', '3HGGK5H45LM705439', 5, 3, 'cars/25.png', 1, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (37, 'Camry', 2021, 'Toyota', 'Sedan', 'XSE4-Cyl, 2.5 Liter', 32574, 301, 25, 'Gasoline', 'Second Row Seating', 'FWD', 'Midnight Black Metallic', '2.5L I4 16V PDI DOHC', '8-Speed Automatic', 'LU939099', '4T1K61AK7LU939099', 5, 5, 'cars/1.png', 0, 1, 'description');
INSERT INTO Backend_car (id, name, year, brand, category, model, price, horsepower, mpg, fuelType, seating, drivetrain, color, engine, transmission, stockid, vin, mileage, expertRating, img, enable, priority, des) VALUES (38, 'Camry', 2021, 'Toyota', 'Sedan', 'XSE4-Cyl, 2.5 Liter', 32574, 301, 25, 'Gasoline', 'Second Row Seating', 'FWD', 'Midnight Black Metallic', '2.5L I4 16V PDI DOHC', '8-Speed Automatic', 'LU939099', '4T1K61AK7LU939099', 5, 5, 'cars/1.png', 0, 1, 'description');